enum RETURN_CODES {
    TOPP_UNSPEC = 0,
    TOPP_OK = 1,
    TOPP_CANNOT_PREPROCESS,
    TOPP_SHORT_TRAJ,
    TOPP_MVC_HIT_ZERO,
    TOPP_CLC_ERROR,
    TOPP_SDBEG_TOO_HIGH,
    TOPP_SDEND_TOO_HIGH,
    TOPP_FWD_HIT_ZERO,
    TOPP_BWD_HIT_ZERO,
    TOPP_FWD_FAIL,
    TOPP_BWD_FAIL
};
